#include "../scripts/sa/Spawn.pwn"

#include "../scripts/sa/Zones/LS.pwn"
#include "../scripts/sa/Zones/SF.pwn"
#include "../scripts/sa/Zones/LV.pwn"
#include "../scripts/sa/Zones/RC.pwn"
#include "../scripts/sa/Zones/FC.pwn"
#include "../scripts/sa/Zones/BC.pwn"
#include "../scripts/sa/Zones/TR.pwn"
#include "../scripts/sa/World/Area69.pwn"
#include "../scripts/sa/World/Ranch.pwn"
#include "../scripts/sa/World/MtChill.pwn"
