new stock 
	ItemType:item_timer			= INVALID_ITEM_TYPE, // required for some crafting
	ItemType:item_explosive		= INVALID_ITEM_TYPE, // can be crafted with phone to make remote explosive
	ItemType:item_battery		= INVALID_ITEM_TYPE, // required for some crafting
	ItemType:item_fusebox		= INVALID_ITEM_TYPE, // required for some crafting

	ItemType:item_FishRod		= INVALID_ITEM_TYPE, // fishing?
	ItemType:item_Taser			= INVALID_ITEM_TYPE, // stuns players (needs anim, or just other hand)
	ItemType:item_LaserPoint	= INVALID_ITEM_TYPE, // combine with explosives to make trip mine
	ItemType:item_MobilePhone	= INVALID_ITEM_TYPE, // remote detonator? communication?
	ItemType:item_Pager			= INVALID_ITEM_TYPE, // same as above
	ItemType:item_Rake			= INVALID_ITEM_TYPE, // rake to the face
	ItemType:item_HotDog		= INVALID_ITEM_TYPE, // eat for hp (add more food if available)
	ItemType:item_EasterEgg		= INVALID_ITEM_TYPE, // open for random stuff, must remove oversized ones
	ItemType:item_Cane			= INVALID_ITEM_TYPE, // bling
	ItemType:item_Bucket		= INVALID_ITEM_TYPE, // put on head... lol
	ItemType:item_GasMask		= INVALID_ITEM_TYPE, // anti poison gas? (need poison gass wep/item!)
	ItemType:item_Flag			= INVALID_ITEM_TYPE, // marking territory
	ItemType:item_CapCase		= INVALID_ITEM_TYPE, // For encasing motion sensor mines
	ItemType:item_MotionSense	= INVALID_ITEM_TYPE, // Used to create mines
	ItemType:item_Canister1		= INVALID_ITEM_TYPE,
	ItemType:item_Canister2		= INVALID_ITEM_TYPE,
	ItemType:item_Canister3		= INVALID_ITEM_TYPE,
	ItemType:item_Clothes		= INVALID_ITEM_TYPE,
	ItemType:item_Pizza			= INVALID_ITEM_TYPE,
	ItemType:item_Burger		= INVALID_ITEM_TYPE,
	ItemType:item_BurgerBox		= INVALID_ITEM_TYPE,
	ItemType:item_Taco			= INVALID_ITEM_TYPE,
	ItemType:item_SmallBox		= INVALID_ITEM_TYPE,
	ItemType:item_AmmoBox1		= INVALID_ITEM_TYPE,
	ItemType:item_AmmoBox2		= INVALID_ITEM_TYPE,
	ItemType:item_AmmoBox3		= INVALID_ITEM_TYPE,
	ItemType:item_Meat			= INVALID_ITEM_TYPE,
	ItemType:item_DeadLeg		= INVALID_ITEM_TYPE,
	ItemType:item_DeadArm		= INVALID_ITEM_TYPE,
	ItemType:item_LongPlank		= INVALID_ITEM_TYPE,
	ItemType:item_GreenGloop	= INVALID_ITEM_TYPE,
	ItemType:item_Capsule		= INVALID_ITEM_TYPE,
	ItemType:item_RadioPole		= INVALID_ITEM_TYPE,
	ItemType:item_SignShot		= INVALID_ITEM_TYPE,
	ItemType:item_Mailbox		= INVALID_ITEM_TYPE,
	ItemType:item_Pumpkin		= INVALID_ITEM_TYPE,
	ItemType:item_Nailbat		= INVALID_ITEM_TYPE,
	ItemType:item_Barbecue		= INVALID_ITEM_TYPE,
	ItemType:item_DeagleLol		= INVALID_ITEM_TYPE;

